// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkaDVMbINCh-h7xiewONFyLSlkjzpBSoY',
    appId: '1:438794452979:android:26a1e2432d09a06efedc86',
    messagingSenderId: '438794452979',
    projectId: 'shopping-list-8e93e',
    databaseURL: 'https://shopping-list-8e93e-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'shopping-list-8e93e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1k8k_y4rHzxgnCObkG6RihJnXsNDV7Qc',
    appId: '1:438794452979:ios:462ac75e46d297a7fedc86',
    messagingSenderId: '438794452979',
    projectId: 'shopping-list-8e93e',
    databaseURL: 'https://shopping-list-8e93e-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'shopping-list-8e93e.firebasestorage.app',
    iosBundleId: 'com.jmartinez.sharedShoppingLists',
  );

}